from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard_view, name="dashboard"),
    path("banners/", views.banner_list, name="banner_list"),
    path("banners/create/", views.banner_create, name="banner_create"),
    path("banners/<int:pk>/edit/", views.banner_edit, name="banner_edit"),
    path("banners/<int:pk>/delete/", views.banner_delete, name="banner_delete"),
    path("pages/", views.page_list, name="page_list"),
    path("pages/create/", views.page_create, name="page_create"),
    path("pages/<int:pk>/edit/", views.page_edit, name="page_edit"),
    path("pages/<int:pk>/delete/", views.page_delete, name="page_delete"),
    path("news/", views.news_admin_list, name="news_admin_list"),
    path("news/create/", views.news_create, name="news_create"),
    path("news/<int:pk>/edit/", views.news_edit, name="news_edit"),
    path("news/<int:pk>/delete/", views.news_delete, name="news_delete"),
    path("messages/", views.message_list, name="message_list"),
    path("messages/<int:pk>/", views.message_detail, name="message_detail"),
    path("messages/<int:pk>/read/", views.message_mark_read, name="message_mark_read"),
    path("messages/<int:pk>/delete/", views.message_delete, name="message_delete"),
    path("api/stats/", views.api_dashboard_stats, name="api_stats"),
    path("api/global-search/", views.api_global_search, name="api_global_search"),
    path("api/monthly-revenue/", views.api_monthly_revenue, name="api_monthly_revenue"),
    path("api/order-status-chart/", views.api_order_status_chart, name="api_order_status"),
    path("api/top-products/", views.api_top_products, name="api_top_products"),
    path("api/visitors/daily/", views.api_visitors_daily, name="api_visitors_daily"),
    path("api/visitors/monthly/", views.api_visitors_monthly, name="api_visitors_monthly"),
    path("api/visitors/summary/", views.api_visitors_summary, name="api_visitors_summary"),
    path("api/top-viewed/", views.api_top_viewed_products, name="api_top_viewed"),
    path("api/search-stats/", views.api_search_stats, name="api_search_stats"),
    path("api/sellers-ranking/", views.api_sellers_ranking, name="api_sellers_ranking"),
    path("api/low-stock/", views.api_low_stock, name="api_low_stock"),
    path("api/conversion/", views.api_conversion_rate, name="api_conversion"),
    path("api/activity/", views.api_recent_activity, name="api_activity"),
]
