# Generated by Django 6.0.3 on 2026-04-08 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminRole',
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='object_repr',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='currency_symbol',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='registration_enabled',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='site_favicon',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
